
export const FETCH_BOOKS_START = "FETCH_BOOKS_START"
export const FETCH_BOOKS_OK = "FETCH_BOOKS_OK"
export const FETCH_BOOKS_ERROR = "FETCH_BOOKS_ERROR"
export const SEARCH_BOOKS_START = "SEARCH_BOOKS_START"
export const SEARCH_BOOKS_OK = "SEARCH_BOOKS_OK"